model_id: meta-llama/Meta-Llama-3.1-8B-Instruct # The name as found on HuggingFace to load the model with
model_kwargs: # passed to AutoModelForCausalLM.from_pretrained
  device_map: auto
add_padding_token: False

qa_formatter_kwargs:
  question_template: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nYou are a helpful assistant<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{question}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
  answer_template: "{answer}<|eot_id|>"

peft_kwargs:
  r: 8
