model_id: microsoft/Phi-3-mini-4k-instruct # The name as found on HuggingFace to load the model with
model_kwargs: # passed to AutoModelForCausalLM.from_pretrained
  device_map: auto
  trust_remote_code: True
add_padding_token: False

qa_formatter_kwargs:
  question_template: "<|system|>\nYou are a helpful assistant.<|end|>\n<|user|>\n{question}<|end|>\n<|assistant|>\n"  # must contain {question}
  answer_template: "{answer}<|end|><|endoftext|>"  # should start with {answer} (any prefix tokens before the answer should be in question_template)

peft_kwargs:  # passed to LoraConfig
  r: 8
