trainer_kwargs: # passed to TrainingArguments
  # Batch size
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 1

  # Core hyperparameters
  learning_rate: 5.e-5
  num_train_epochs: 10

  # Evaluation
  evaluation_strategy: steps

  # Logging
  logging_strategy: steps
  logging_steps: 0.5 # can be float or int

  # Early stopping
  load_best_model_at_end: true
  metric_for_best_model: eval_loss
  save_strategy: steps
  save_total_limit: 1

  # Outputs
  output_dir: output
# Early stopping kwargs (only needed if save strategy is not null)
early_stopping_kwargs:
  patience: 2
