trainer_kwargs: # passed to TrainingArguments
  # Memory optimization
  bf16: True

  # Batch size
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 1

  # Core hyperparameters
  learning_rate: 5.e-5
  num_train_epochs: 25

  # Evaluation
  evaluation_strategy: epoch

  # Logging
  logging_strategy: epoch

  # Early stopping
  save_strategy: epoch
  save_total_limit: 1

  # Outputs
  output_dir: output

peft_kwargs:  # passed to LoraConfig
  r: 8
