# All of thse should be contained under configs/type/
data_config: example_tofu_1
model_config: gpt2_forget
model_path: temp/20240507-232355-483306

forget_class: difference

# Seed for random components
seed: 42

use_wandb: true
wandb_config:
  entity: turing-arc
  project: selective-forgetting
  log_model: "false"
  group: debug-runs
