# All of thse should be contained under configs/type/
data_config: example_tofu_1
model_config: gpt2_short
model_path: gpt2

forget_class: ascent

# Seed for random components
seed: 42

use_wandb: false
wandb_config:
  entity: turing-arc
  project: selective-forgetting
  log_model: "false"
  group: debug-runs
